#version: '3.8'
## 添加 volumes 定义
services:
  mysql:
    image: mysql:8.0
    container_name: homework-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-homeworksystem}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 10
    #Go 应用服务
  go-app:
    image: xieyuxuan/homeworksystem:v1.0.0
    container_name: homework-go-app
    restart: always
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - mysql
    environment:
      #数据库配置
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE:-homeworksystem}
      DB_USER: ${MYSQL_USER:-user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-user}

      #应用配置
      JWT_SECRET: ${JWT_SECRET:-xieasdfasdfasdfasdfsadfasfdsadfsaf}
